### ISSUE TITLE
All objects in canvas able to move

### ISSUE THREAD

**Issue by HarryMills** [Sloths/Project-Three#11]
Movement code to move treasure allows all items in canvas to be able to move. This should not be the case.
![image](https://cloud.githubusercontent.com/assets/8501727/6432109/30ac0cb4-c03e-11e4-8d22-ec01df13cfe6.png)

**Comment by Gurjmath** [comment]
problem sorted, only issue is that trap and treasure inherit from same class. Both objects move with mouse, this should be only for treasure object.
