### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by Adam131** [Sloths/Project-Three#20]
When the program is re-started after the timer runs down to 00:00, the timer image flickers

**Comment by JessicaPearson** [comment]
The countdown clock is supposed to go to the grey clock image to indicate the countdown is finished to the user.

**Comment by Adam131** [comment]
When the program is finished, and the start button is pressed to re run the program again, it flickers.

**Comment by JessicaPearson** [comment]
Fixed the issue using intPlay to register the number of clicks on Start
