### ISSUE TITLE
LVL3 - Treasure List Sorting Algorithm.

### ISSUE THREAD

**Issue by ghost** [Sloths/Project-Three#8]
Show unordered list of collected treasure and the ordered. Or an animation of the sorting algorithm in action.

**Comment by HarryMills** [comment]
![image](https://cloud.githubusercontent.com/assets/8501727/6487946/3d9e8a78-c28c-11e4-9549-a4d08528032e.png)
Bubble sort algorithm has been implemented to sort treasure items by value, with most valuable treasure first
